SET SCHEMA PUBLIC;
DROP TABLE IF EXISTS phone;
DROP TABLE IF EXISTS user_entity;
CREATE TABLE user_entity (
    ID VARCHAR(256) PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100),
    PASSWORD VARCHAR(256) NOT NULL,
    CREATED DATE NOT NULL,
    MODIFIED DATE NOT NULL,
    LAST_LOGIN DATE NULL,
    TOKEN VARCHAR(512) NULL,
    ACTIVE BIT NOT NULL
);

CREATE TABLE phone (
    ID VARCHAR(256) NOT NULL PRIMARY KEY,
    NUMBER INT NOT NULL,
    CITY_CODE INT NOT NULL,
    COUNTRY_CODE INT NOT NULL,
    USER_ENTITY_ID VARCHAR(256) NULL,
    FOREIGN KEY (USER_ENTITY_ID) REFERENCES user_entity(ID)
);

//Password: 123
INSERT INTO user_entity  (ID, EMAIL, NAME, PASSWORD, CREATED, MODIFIED, LAST_LOGIN, TOKEN, ACTIVE)
    VALUES ( '123456', 'nic.lar.universidad@gmail.com', 'Esteban Nicolás Larena',
            '$2a$10$/f0bwMoyv4VtpqGTPk7ALO4z4BAersmzMZ3G5nZfltF9geW07LFYS',
            CURRENT_DATE(), CURRENT_DATE(), null, null, true)