SET SCHEMA PUBLIC;
DROP TABLE IF EXISTS phone;
DROP TABLE IF EXISTS user_entity;
CREATE TABLE user_entity (
    ID VARCHAR(256) PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100),
    PASSWORD VARCHAR(256) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP NOT NULL,
    LAST_LOGIN TIMESTAMP NULL,
    TOKEN VARCHAR(512) NULL,
    ACTIVE BIT NOT NULL
);

CREATE TABLE phone (
    ID VARCHAR(256) NOT NULL PRIMARY KEY,
    NUMBER INT NOT NULL,
    CITY_CODE INT NOT NULL,
    COUNTRY_CODE INT NOT NULL,
    USER_ENTITY_ID VARCHAR(256) NULL,
    FOREIGN KEY (USER_ENTITY_ID) REFERENCES user_entity(ID)
);

CREATE TABLE user_entity_phones (
       USER_ENTITY_ID VARCHAR(256) NULL,
       PHONES_ID VARCHAR(256) NULL,
       FOREIGN KEY (USER_ENTITY_ID) REFERENCES user_entity(ID),
       FOREIGN KEY (PHONES_ID) REFERENCES phone(ID)
);

CREATE TABLE session (
       ID VARCHAR(256) NOT NULL PRIMARY KEY,
       EXPIRES_AT TIMESTAMP NOT NULL,
       TOKEN VARCHAR(512) NOT NULL,
       USER_ID VARCHAR(256) NULL,
       ACTIVE BIT NOT NULL,
       FOREIGN KEY (USER_ID) REFERENCES user_entity(ID)
);